#!/usr/bin/bash

# minikube installer script
# Author: Yahaya Azeez Adebayo
# Date: 2/11/2024
# Usage: bash minikube-install.sh

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

minikube start

echo "Happy hacking 🤖"
